import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Login from '../UI/organism/login/index'

export default function Home() {

  return (
    <div className={styles.container}>
      
      <Head>
        <title>Sun Wu Kong</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

     <main className={styles.main}>
            <Login/>
      </main>

    </div>
  )
}
